name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install mockery
        run: go get github.com/vektra/mockery/v2/.../

      - name: Create mocks
        run: mockery --all --inpackage

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -coverprofile=coverage.out -covermode=atomic ./...

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
