name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  mockery-container:
    runs-on: ubuntu-latest
    container:
      image: vektra/mockery
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
    steps:
      - name: Run mockery from container
        run: docker run -v ${{ github.workspace }}:/src -w /src vektra/mockery --all --inpackage

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Install mockery
        run: go get github.com/vektra/mockery/v2/.../

      - name: Create mocks
        run: mockery --all --inpackage

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -coverprofile=coverage.out -covermode=atomic ./...

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
