# https://github.com/marketplace/actions/todo-to-issue

name: "todo-to-issue"
on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v5.1.9"
        id: "todo"